import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "ar";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.hr": "Human Resources",
    "nav.employees": "Employees",
    "nav.contracts": "Contracts",
    "nav.payroll": "Payroll",
    "nav.attendance": "Attendance",
    "nav.accounting": "Accounting",
    "nav.revenue": "Revenue",
    "nav.expenses": "Expenses",
    "nav.financial": "Financial Overview",
    "nav.branches": "Branches",
    "nav.inventory": "Inventory",
    "nav.tasks": "Tasks",
    "nav.reports": "Reports & Analytics",
    "nav.ai": "AI Assistant",
    "nav.import": "Data Import",
    "nav.settings": "Settings",
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Welcome back",
    "dashboard.totalEmployees": "Total Employees",
    "dashboard.activeContracts": "Active Contracts",
    "dashboard.expiringContracts": "Expiring Soon",
    "dashboard.todayAttendance": "Today's Attendance",
    "dashboard.lateArrivals": "Late Arrivals",
    "dashboard.earlyLeave": "Early Leave",
    "dashboard.monthlyPayroll": "Monthly Payroll",
    "dashboard.totalRevenue": "Total Revenue",
    "dashboard.totalExpenses": "Total Expenses",
    "dashboard.netProfit": "Net Profit",
    "dashboard.lowStockAlerts": "Low Stock Alerts",
    "dashboard.openTasks": "Open Tasks",
    "dashboard.overdueTasks": "Overdue Tasks",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.branchPerformance": "Branch Performance",
    "dashboard.aiInsights": "AI Insights",
    // Common
    "common.add": "Add",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.export": "Export",
    "common.view": "View",
    "common.actions": "Actions",
    "common.status": "Status",
    "common.date": "Date",
    "common.name": "Name",
    "common.email": "Email",
    "common.phone": "Phone",
    "common.branch": "Branch",
    "common.department": "Department",
    "common.amount": "Amount",
    "common.notes": "Notes",
    "common.upload": "Upload",
    "common.download": "Download",
    "common.loading": "Loading...",
    "common.noData": "No data available",
    "common.confirm": "Confirm",
    "common.yes": "Yes",
    "common.no": "No",
    "common.all": "All",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.total": "Total",
    "common.from": "From",
    "common.to": "To",
    "common.generate": "Generate",
    "common.print": "Print",
    "common.close": "Close",
    "common.back": "Back",
    "common.next": "Next",
    "common.submit": "Submit",
    "common.reset": "Reset",
    "common.required": "Required",
    "common.optional": "Optional",
    "common.currency": "SAR",
    "common.of": "of",
    "common.rows": "rows",
    // Employees
    "employees.title": "Employees",
    "employees.add": "Add Employee",
    "employees.edit": "Edit Employee",
    "employees.firstName": "First Name",
    "employees.lastName": "Last Name",
    "employees.employeeCode": "Employee Code",
    "employees.jobTitle": "Job Title",
    "employees.hireDate": "Hire Date",
    "employees.erpRole": "System Role",
    "employees.gender": "Gender",
    "employees.nationality": "Nationality",
    "employees.nationalId": "National ID",
    "employees.dateOfBirth": "Date of Birth",
    "employees.address": "Address",
    "employees.documents": "Documents",
    "employees.male": "Male",
    "employees.female": "Female",
    "employees.other": "Other",
    "employees.active": "Active",
    "employees.inactive": "Inactive",
    "employees.on_leave": "On Leave",
    "employees.terminated": "Terminated",
    // Contracts
    "contracts.title": "Contracts",
    "contracts.add": "Add Contract",
    "contracts.contractType": "Contract Type",
    "contracts.startDate": "Start Date",
    "contracts.endDate": "End Date",
    "contracts.salary": "Contract Salary",
    "contracts.active": "Active",
    "contracts.expired": "Expired",
    "contracts.pending_renewal": "Pending Renewal",
    "contracts.terminated": "Terminated",
    "contracts.expiringIn": "Expiring in",
    "contracts.days": "days",
    // Payroll
    "payroll.title": "Payroll",
    "payroll.salaryStructure": "Salary Structure",
    "payroll.basicSalary": "Basic Salary",
    "payroll.housingAllowance": "Housing Allowance",
    "payroll.transportAllowance": "Transport Allowance",
    "payroll.otherAllowances": "Other Allowances",
    "payroll.socialInsurance": "Social Insurance",
    "payroll.taxDeduction": "Tax Deduction",
    "payroll.otherDeductions": "Other Deductions",
    "payroll.totalAllowances": "Total Allowances",
    "payroll.totalDeductions": "Total Deductions",
    "payroll.bonus": "Bonus",
    "payroll.netSalary": "Net Salary",
    "payroll.generatePayroll": "Generate Payroll",
    "payroll.month": "Month",
    "payroll.year": "Year",
    "payroll.draft": "Draft",
    "payroll.approved": "Approved",
    "payroll.paid": "Paid",
    "payroll.salarySlip": "Salary Slip",
    // Attendance
    "attendance.title": "Attendance",
    "attendance.checkIn": "Check In",
    "attendance.checkOut": "Check Out",
    "attendance.present": "Present",
    "attendance.absent": "Absent",
    "attendance.late": "Late",
    "attendance.early_leave": "Early Leave",
    "attendance.on_leave": "On Leave",
    "attendance.holiday": "Holiday",
    "attendance.delayMinutes": "Delay (min)",
    "attendance.earlyLeaveMinutes": "Early Leave (min)",
    "attendance.violations": "Violations",
    "attendance.addRecord": "Add Record",
    "attendance.adjust": "Adjust",
    // Accounting
    "accounting.title": "Accounting",
    "accounting.revenue": "Revenue",
    "accounting.expenses": "Expenses",
    "accounting.category": "Category",
    "accounting.description": "Description",
    "accounting.reference": "Reference",
    "accounting.addRevenue": "Add Revenue",
    "accounting.addExpense": "Add Expense",
    "accounting.financialOverview": "Financial Overview",
    "accounting.revenueVsExpenses": "Revenue vs Expenses",
    "accounting.profitLoss": "Profit / Loss",
    // Branches
    "branches.title": "Branches",
    "branches.add": "Add Branch",
    "branches.edit": "Edit Branch",
    "branches.address": "Address",
    "branches.manager": "Manager",
    "branches.performance": "Performance",
    // Inventory
    "inventory.title": "Inventory",
    "inventory.add": "Add Item",
    "inventory.itemCode": "Item Code",
    "inventory.category": "Category",
    "inventory.unit": "Unit",
    "inventory.quantity": "Quantity",
    "inventory.minimumStock": "Minimum Stock",
    "inventory.unitCost": "Unit Cost",
    "inventory.stockIn": "Stock In",
    "inventory.stockOut": "Stock Out",
    "inventory.transfer": "Transfer",
    "inventory.lowStock": "Low Stock",
    "inventory.history": "History",
    "inventory.adjustment": "Adjustment",
    // Tasks
    "tasks.title": "Tasks",
    "tasks.add": "Add Task",
    "tasks.assignTo": "Assign To",
    "tasks.priority": "Priority",
    "tasks.dueDate": "Due Date",
    "tasks.low": "Low",
    "tasks.medium": "Medium",
    "tasks.high": "High",
    "tasks.urgent": "Urgent",
    "tasks.pending": "Pending",
    "tasks.in_progress": "In Progress",
    "tasks.completed": "Completed",
    "tasks.overdue": "Overdue",
    "tasks.cancelled": "Cancelled",
    "tasks.comments": "Comments",
    "tasks.addComment": "Add Comment",
    // Reports
    "reports.title": "Reports & Analytics",
    "reports.hrReport": "HR Report",
    "reports.payrollReport": "Payroll Report",
    "reports.attendanceReport": "Attendance Report",
    "reports.financialReport": "Financial Report",
    "reports.inventoryReport": "Inventory Report",
    "reports.taskReport": "Task Report",
    "reports.branchReport": "Branch Report",
    "reports.dateRange": "Date Range",
    "reports.generate": "Generate Report",
    // AI
    "ai.title": "AI Assistant",
    "ai.subtitle": "Ask questions about employees, attendance, finances, and more",
    "ai.placeholder": "Ask me anything about your organization...",
    "ai.send": "Send",
    "ai.thinking": "Thinking...",
    "ai.suggestions": "Quick suggestions",
    // Auth
    "auth.login": "Login",
    "auth.logout": "Logout",
    "auth.profile": "Profile",
    // Roles
    "role.super_admin": "Super Admin",
    "role.hr_manager": "HR Manager",
    "role.accountant": "Accountant",
    "role.branch_manager": "Branch Manager",
    "role.inventory_officer": "Inventory Officer",
    "role.department_manager": "Department Manager",
    "role.employee": "Employee",
  },
  ar: {
    // Navigation
    "nav.dashboard": "لوحة التحكم",
    "nav.hr": "الموارد البشرية",
    "nav.employees": "الموظفون",
    "nav.contracts": "العقود",
    "nav.payroll": "الرواتب",
    "nav.attendance": "الحضور والانصراف",
    "nav.accounting": "المحاسبة",
    "nav.revenue": "الإيرادات",
    "nav.expenses": "المصروفات",
    "nav.financial": "النظرة المالية",
    "nav.branches": "الفروع",
    "nav.inventory": "المخزون",
    "nav.tasks": "المهام",
    "nav.reports": "التقارير والتحليلات",
    "nav.ai": "المساعد الذكي",
    "nav.import": "استيراد البيانات",
    "nav.settings": "الإعدادات",
    // Dashboard
    "dashboard.title": "لوحة التحكم",
    "dashboard.welcome": "مرحباً بعودتك",
    "dashboard.totalEmployees": "إجمالي الموظفين",
    "dashboard.activeContracts": "العقود النشطة",
    "dashboard.expiringContracts": "تنتهي قريباً",
    "dashboard.todayAttendance": "حضور اليوم",
    "dashboard.lateArrivals": "التأخيرات",
    "dashboard.earlyLeave": "الانصراف المبكر",
    "dashboard.monthlyPayroll": "الرواتب الشهرية",
    "dashboard.totalRevenue": "إجمالي الإيرادات",
    "dashboard.totalExpenses": "إجمالي المصروفات",
    "dashboard.netProfit": "صافي الربح",
    "dashboard.lowStockAlerts": "تنبيهات المخزون",
    "dashboard.openTasks": "المهام المفتوحة",
    "dashboard.overdueTasks": "المهام المتأخرة",
    "dashboard.recentActivity": "النشاط الأخير",
    "dashboard.branchPerformance": "أداء الفروع",
    "dashboard.aiInsights": "رؤى الذكاء الاصطناعي",
    // Common
    "common.add": "إضافة",
    "common.edit": "تعديل",
    "common.delete": "حذف",
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.export": "تصدير",
    "common.view": "عرض",
    "common.actions": "الإجراءات",
    "common.status": "الحالة",
    "common.date": "التاريخ",
    "common.name": "الاسم",
    "common.email": "البريد الإلكتروني",
    "common.phone": "الهاتف",
    "common.branch": "الفرع",
    "common.department": "القسم",
    "common.amount": "المبلغ",
    "common.notes": "ملاحظات",
    "common.upload": "رفع",
    "common.download": "تحميل",
    "common.loading": "جاري التحميل...",
    "common.noData": "لا توجد بيانات",
    "common.confirm": "تأكيد",
    "common.yes": "نعم",
    "common.no": "لا",
    "common.all": "الكل",
    "common.active": "نشط",
    "common.inactive": "غير نشط",
    "common.total": "الإجمالي",
    "common.from": "من",
    "common.to": "إلى",
    "common.generate": "إنشاء",
    "common.print": "طباعة",
    "common.close": "إغلاق",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.submit": "إرسال",
    "common.reset": "إعادة تعيين",
    "common.required": "مطلوب",
    "common.optional": "اختياري",
    "common.currency": "ر.س",
    "common.of": "من",
    "common.rows": "صفوف",
    // Employees
    "employees.title": "الموظفون",
    "employees.add": "إضافة موظف",
    "employees.edit": "تعديل موظف",
    "employees.firstName": "الاسم الأول",
    "employees.lastName": "اسم العائلة",
    "employees.employeeCode": "رمز الموظف",
    "employees.jobTitle": "المسمى الوظيفي",
    "employees.hireDate": "تاريخ التوظيف",
    "employees.erpRole": "الدور في النظام",
    "employees.gender": "الجنس",
    "employees.nationality": "الجنسية",
    "employees.nationalId": "رقم الهوية",
    "employees.dateOfBirth": "تاريخ الميلاد",
    "employees.address": "العنوان",
    "employees.documents": "المستندات",
    "employees.male": "ذكر",
    "employees.female": "أنثى",
    "employees.other": "آخر",
    "employees.active": "نشط",
    "employees.inactive": "غير نشط",
    "employees.on_leave": "في إجازة",
    "employees.terminated": "منتهي الخدمة",
    // Contracts
    "contracts.title": "العقود",
    "contracts.add": "إضافة عقد",
    "contracts.contractType": "نوع العقد",
    "contracts.startDate": "تاريخ البداية",
    "contracts.endDate": "تاريخ الانتهاء",
    "contracts.salary": "راتب العقد",
    "contracts.active": "نشط",
    "contracts.expired": "منتهي",
    "contracts.pending_renewal": "في انتظار التجديد",
    "contracts.terminated": "محلول",
    "contracts.expiringIn": "ينتهي خلال",
    "contracts.days": "أيام",
    // Payroll
    "payroll.title": "الرواتب",
    "payroll.salaryStructure": "هيكل الراتب",
    "payroll.basicSalary": "الراتب الأساسي",
    "payroll.housingAllowance": "بدل السكن",
    "payroll.transportAllowance": "بدل المواصلات",
    "payroll.otherAllowances": "بدلات أخرى",
    "payroll.socialInsurance": "التأمين الاجتماعي",
    "payroll.taxDeduction": "خصم الضريبة",
    "payroll.otherDeductions": "خصومات أخرى",
    "payroll.totalAllowances": "إجمالي البدلات",
    "payroll.totalDeductions": "إجمالي الخصومات",
    "payroll.bonus": "المكافأة",
    "payroll.netSalary": "صافي الراتب",
    "payroll.generatePayroll": "إنشاء كشف الرواتب",
    "payroll.month": "الشهر",
    "payroll.year": "السنة",
    "payroll.draft": "مسودة",
    "payroll.approved": "معتمد",
    "payroll.paid": "مدفوع",
    "payroll.salarySlip": "قسيمة الراتب",
    // Attendance
    "attendance.title": "الحضور والانصراف",
    "attendance.checkIn": "تسجيل الحضور",
    "attendance.checkOut": "تسجيل الانصراف",
    "attendance.present": "حاضر",
    "attendance.absent": "غائب",
    "attendance.late": "متأخر",
    "attendance.early_leave": "انصراف مبكر",
    "attendance.on_leave": "في إجازة",
    "attendance.holiday": "إجازة رسمية",
    "attendance.delayMinutes": "التأخير (دقيقة)",
    "attendance.earlyLeaveMinutes": "الانصراف المبكر (دقيقة)",
    "attendance.violations": "المخالفات",
    "attendance.addRecord": "إضافة سجل",
    "attendance.adjust": "تعديل",
    // Accounting
    "accounting.title": "المحاسبة",
    "accounting.revenue": "الإيرادات",
    "accounting.expenses": "المصروفات",
    "accounting.category": "الفئة",
    "accounting.description": "الوصف",
    "accounting.reference": "المرجع",
    "accounting.addRevenue": "إضافة إيراد",
    "accounting.addExpense": "إضافة مصروف",
    "accounting.financialOverview": "النظرة المالية",
    "accounting.revenueVsExpenses": "الإيرادات مقابل المصروفات",
    "accounting.profitLoss": "الربح / الخسارة",
    // Branches
    "branches.title": "الفروع",
    "branches.add": "إضافة فرع",
    "branches.edit": "تعديل فرع",
    "branches.address": "العنوان",
    "branches.manager": "المدير",
    "branches.performance": "الأداء",
    // Inventory
    "inventory.title": "المخزون",
    "inventory.add": "إضافة صنف",
    "inventory.itemCode": "كود الصنف",
    "inventory.category": "الفئة",
    "inventory.unit": "الوحدة",
    "inventory.quantity": "الكمية",
    "inventory.minimumStock": "الحد الأدنى",
    "inventory.unitCost": "تكلفة الوحدة",
    "inventory.stockIn": "إدخال مخزون",
    "inventory.stockOut": "إخراج مخزون",
    "inventory.transfer": "نقل",
    "inventory.lowStock": "مخزون منخفض",
    "inventory.history": "السجل",
    "inventory.adjustment": "تعديل",
    // Tasks
    "tasks.title": "المهام",
    "tasks.add": "إضافة مهمة",
    "tasks.assignTo": "تعيين إلى",
    "tasks.priority": "الأولوية",
    "tasks.dueDate": "تاريخ الاستحقاق",
    "tasks.low": "منخفضة",
    "tasks.medium": "متوسطة",
    "tasks.high": "عالية",
    "tasks.urgent": "عاجلة",
    "tasks.pending": "معلقة",
    "tasks.in_progress": "قيد التنفيذ",
    "tasks.completed": "مكتملة",
    "tasks.overdue": "متأخرة",
    "tasks.cancelled": "ملغاة",
    "tasks.comments": "التعليقات",
    "tasks.addComment": "إضافة تعليق",
    // Reports
    "reports.title": "التقارير والتحليلات",
    "reports.hrReport": "تقرير الموارد البشرية",
    "reports.payrollReport": "تقرير الرواتب",
    "reports.attendanceReport": "تقرير الحضور",
    "reports.financialReport": "التقرير المالي",
    "reports.inventoryReport": "تقرير المخزون",
    "reports.taskReport": "تقرير المهام",
    "reports.branchReport": "تقرير الفروع",
    "reports.dateRange": "نطاق التاريخ",
    "reports.generate": "إنشاء التقرير",
    // AI
    "ai.title": "المساعد الذكي",
    "ai.subtitle": "اسأل عن الموظفين والحضور والمالية والمزيد",
    "ai.placeholder": "اسألني أي شيء عن مؤسستك...",
    "ai.send": "إرسال",
    "ai.thinking": "جاري التفكير...",
    "ai.suggestions": "اقتراحات سريعة",
    // Auth
    "auth.login": "تسجيل الدخول",
    "auth.logout": "تسجيل الخروج",
    "auth.profile": "الملف الشخصي",
    // Roles
    "role.super_admin": "مدير النظام",
    "role.hr_manager": "مدير الموارد البشرية",
    "role.accountant": "محاسب",
    "role.branch_manager": "مدير الفرع",
    "role.inventory_officer": "مسؤول المخزون",
    "role.department_manager": "مدير القسم",
    "role.employee": "موظف",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (key) => key,
  isRTL: false,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem("erp-lang");
    return (saved as Language) || "en";
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem("erp-lang", newLang);
  };

  const isRTL = lang === "ar";

  useEffect(() => {
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, [lang, isRTL]);

  const t = (key: string): string => {
    return translations[lang][key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
